---
title: "R Notebook"
output: html_notebook
---

# To do

- change to xgboost?
- make country predictions

# Set up

```{r}
library(magrittr)

psce_unq <- read.csv("psce_unq.csv")
country_species <- readRDS("country_species.rds")
inds_df <- read.csv("inds_df.csv")
inva_db <- read.csv("inva_db_clean.csv")

inds_df$iso2c[is.na(inds_df$iso2c)] <- "NA" # Namibia gets mistaken for missing data
```

# Fit random forest without country data

Log and scale cost data

```{r}
psce_unq$log_Cost <- log(psce_unq$Cost)
```

Partition data

```{r}
set.seed(1)

part_ind <- 
  caret::createDataPartition(y=psce_unq$log_Cost, 
                             p=0.7, 
                             list=FALSE)

psce_train <- psce_unq[part_ind, ]
psce_test <- psce_unq[-part_ind, ]
```

Fit Random Forest model

```{r}
set.seed(1)

train_control <-
  caret::trainControl(method = 'repeatedcv', 
                      number = 5, 
                      repeats = 3)

psce_rf <- 
  caret::train(log_Cost ~ Sector + Phylum + Environment + Geographic_region + Type_of_cost, 
               method='rf', 
               trControl= train_control,
               metric='RMSE',
               data = psce_train)

saveRDS(psce_rf, "psce_rf.rds")
```

Cross-validate

```{r}
psce_rf <- readRDS("psce_rf.rds")

# psce_rf$finalModel
psce_test <- psce_test[!psce_test$Class %in% c("Osteichthyes", "Pisoniviricetes"),]

pred_psce_rf <- 
  predict(psce_rf, 
          psce_test)

1 - mean((pred_psce_rf - psce_test$log_Cost)^2)/var(psce_test$log_Cost)
```

Check variable importance with Boruta

```{r}
psce_boruta <- 
  Boruta::Boruta(log_Cost ~ Sector + Phylum + Environment + Geographic_region + Type_of_cost,
                 psce_train)

plot(psce_boruta)
```

# Fit random forest with country data

```{r}
psce_train$iso2 <- 
  rgbif::isocodes$code[match(psce_train$Country,
                             rgbif::isocodes$name)]

psce_test$iso2 <- 
  rgbif::isocodes$code[match(psce_test$Country,
                             rgbif::isocodes$name)]

psce_train_preds <-
  dplyr::left_join(psce_train, inds_df, by = c("iso2" = "iso2c"))

psce_train_preds <- psce_train_preds[,-c(2,6,7,9,11)]

psce_test_preds <-
  dplyr::left_join(psce_test, inds_df, by = c("iso2" = "iso2c"))

psce_test_preds <- psce_test_preds[,-c(2,6,7,9,11)]
```

```{r}
psce_boruta_preds <- 
  Boruta::Boruta(log_Cost ~ .,
                 psce_train_preds[complete.cases(psce_train_preds),])

selected_preds <-
  names(psce_boruta_preds$finalDecision)[psce_boruta_preds$finalDecision == "Confirmed"]
```

```{r}
psce_train_selected <- 
  psce_train_preds[c(6, which(names(psce_train_preds) %in% selected_preds))]
```

Fit Random Forest model

```{r}
set.seed(1)

train_control <-
  caret::trainControl(method = 'repeatedcv', 
                      number = 5, 
                      repeats = 3, 
                      search="random",
                      verbose = TRUE)

psce_rf_preds <- 
  caret::train(log_Cost ~ ., 
               method='rf', 
               trControl= train_control,
               metric='RMSE',
               data = psce_train_selected[complete.cases(psce_train_selected),],
               tuneLength = 15)

saveRDS(psce_rf_preds, "psce_rf_preds.rds")
```

Cross-validate

```{r}
psce_rf_preds <- readRDS("psce_rf_preds.rds")

# psce_rf_preds$finalModel

pred_psce_rf_preds <- 
  predict(psce_rf_preds, 
          psce_test_preds[complete.cases(psce_test_preds),])

1 - mean((pred_psce_rf_preds - 
            psce_test_preds[complete.cases(psce_test_preds),]$log_Cost)^2)/
  var(psce_test_preds[complete.cases(psce_test_preds),]$log_Cost)
```

# Make predictions for countries

```{r}
country_region <- read.csv("country_region.csv")

inds_df$Geographic_region <- 
  country_region$Geographic_region[match(inds_df$iso2c, 
                                         country_region$iso2)]

# assign regions for countries not in the data set

inds_df$Geographic_region[inds_df$iso2c %in% c("AO","BI","BF","BW","CF","CG","KM","CV","DJ","DZ",
                                               "EG","ER","GA","GN","GM","GW","GQ","LR","LS","MA",
                                               "MG","MR","MU","NA","SD","SL","SO","SS","ST","SZ",
                                               "SC","TD","TN")] <- "Africa"

inds_df$Geographic_region[inds_df$iso2c %in% c("AF","AE","AM","AZ","BD","BH","GE","IR","IQ","IL",
                                               "JO","KZ","KG","KR","KW","LB","MN","NP","OM","KP",
                                               "QA","SA","SY","TJ","TM","UZ","YE")] <- "Asia"

inds_df$Geographic_region[inds_df$iso2c %in% c("AG","BS","BB","DM","HT","LC","NR","TT","VC")] <-
  "Central America"

inds_df$Geographic_region[inds_df$iso2c %in% c("AD","BE","EE","IE","LI","LU","LV","SM","MC")] <-
  "Europe"

inds_df$Geographic_region[inds_df$iso2c %in% c("FM","KI","MH","PW","PG","SB","TO","TV","VU",
                                               "WS")] <- "Europe"

inds_df$Geographic_region[inds_df$iso2c %in% c("GY")] <- "South America"

inds_df$Geographic_region[inds_df$iso2c %in% c("US")] <- "North America" # One entry for puerto rico mixed this up
```

```{r}
un_members <- read.csv("un_members.csv")
un_members$iso2 <- stringr::str_sub(un_members$iso2, 1, 2)

inva_db$Phylum[inva_db$Species == "Cryptotermes brevis"] <- "Arthropoda"

country_species <-
  country_species[country_species$country %in% un_members$iso2,]

country_species <-
  country_species[country_species$sp %in% inva_db$Species,]

country_species <-
  country_species[!country_species$sp %in% c("Liriomyza sativae"),]

costs_per_country <-
  pbapply::pbapply(country_species, 1, function(r){
    
    pred_sp <- 
      inva_db[inva_db$Species == r[1], 
              which(names(inva_db) %in% c("Impacted_sector", 
                                          "Phylum",
                                          "Environment",
                                          "Type_of_cost_merged"))] %>% 
      unique
    
    pred_sp <- pred_sp[complete.cases(pred_sp),]
    
    names(pred_sp)[3:4] <- c("Sector", "Type_of_cost")
    
    pred_cntr <- inds_df[inds_df$iso2c == r[2],]
    
    all_preds <- cbind(pred_sp, pred_cntr)
    
    cost_estimate <- predict(psce_rf_preds, all_preds)
    
    cbind(pred_sp, cost = cost_estimate, country = r[2])
    
  }) %>% 
  do.call(rbind, .) %>% 
  dplyr::group_by(Phylum, Environment, Sector, Type_of_cost, country) %>% 
  dplyr::summarise(Cost = sum(exp(cost)))

write.csv(costs_per_country, "costs_per_country.csv", row.names = FALSE)
```